# -*- coding: utf-8 -*-
"""Pyspark_Rank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Wiwjptv-87beUsjxyT1DJAJY4Z-gmLt
"""



!pip install pyspark

import pyspark

from pyspark.sql.functions import *
from pyspark.sql.functions import asc,desc
from pyspark.sql.window import Window
from pyspark.sql.functions import rank

from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession
c = pyspark.SparkConf().setAppName("test_app").setMaster("local")
sc = pyspark.SparkContext(conf = c)
spark = SparkSession(sc)

from pyspark.sql.window import Window
from pyspark.sql.functions import rank

data = [
        (1, "Karthi",80,"NC"),
        (2, "Amy",80,"NY"),
        (3, "Jack",94,"NY"),
        (4, "Camellia",40,"NC"),
        (5, "Lucy",90,"NY"),
        (6,"Thomas",50,"NY"),
        (7,"Erwin",45,"NC"),
        (8,"Jones",45,"NC")
       ]
column = ["Id","Name","Mark","City"]
df = spark.createDataFrame(data,column)
df.show()

winRes = Window().orderBy(desc("Mark"))
df = df.withColumn('Rank',rank().over(winRes))
df.show(10)

WinRes1 = Window.partitionBy("City").orderBy(desc("Mark"))
df=df.withColumn("Rank_byCity",rank().over(WinRes1))
df.select(["Id","Name","Mark","City","Rank_byCity"]).show()

from google.colab import drive
drive.mount('/content/drive')