# -*- coding: utf-8 -*-
"""Pyspark_Lag&Lead.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f-jbojOtR5zNNwroPcc0g-zsXIbd2K1S
"""

!pip install pyspark

import pyspark

from pyspark.sql.functions import *
from pyspark.sql.functions import asc,desc
from pyspark.sql.window import Window

from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession
c = pyspark.SparkConf().setAppName("test_app").setMaster("local")
sc = pyspark.SparkContext(conf = c)
spark = SparkSession(sc)

data = [
        (2014,"Products",20000),
        (2015,"Products",4000),
        (2016,"Products",6000),
        (2017,"Products",8000),
        (2018,"Products",10000),
        (2014,"Books",3000),
        (2015,"Books",9000),
        (2016,"Books",11000),
        (2017,"Books",15000),
        (2018,"Books",220000)

]
columns = ["year","name","sales"]
df = spark.createDataFrame(data,columns)

winres = Window.orderBy(("year")).partitionBy("name")
df = df.withColumn("lag_col",lag("sales",1).over(winres))
df.show()

##df = df.withColumn("Growth%",(round(((col("sales")-col("lag_col"))/col("lag_col"))*100),2))
df = df.withColumn("Growth%",round(((col("sales")-col("lag_col"))/col("lag_col")*100),2))
df.show()

()